<?php
/**
 * Lists Categories in admin context.
 *
 * Categories are listed and operational links are generated by their id.
 *
 * @author Midori Kocak 2014
 *
 */
?>
<h2>Categories</h2>
<table>
	<thead>
		<tr>
			<th>Id</th>
			<th>Title</th>
			<th>Actions</th>
		</tr>
	</thead>
	<tbody>
    <?php
    foreach ($categories as $category) :
        ?>
        <tr>
			<td><?= $category['id'] ?></td>
			<td><?= htmlspecialchars($category['title']) ?></td>
			<td><a
				href="<?= LINK_PREFIX ?>/Categories/Edit/<?= $category['id'] ?>">Update</a>
				<a
				href="<?= LINK_PREFIX ?>/Categories/Delete/<?= $category['id'] ?>">Delete</a></td>
		</tr>
    <?php
    endforeach
    ;
    ?>
    </tbody>
</table>